spring.application.name=fintech-backend
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
spring.data.redis.host=localhost
spring.data.redis.port=6379
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never